[package]
edition = "2021"
name = "render-node-mre"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.42.0"
